In [2]:
import numpy as np
X= np.array([[1, 0, 1, 1],
       [1, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [0, 1, 1, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])
y= np.array([1, 0, 0, 1, 1, 1, 1, 0, 0, 1])

In [3]:
# calculate entropy
def entropy(y):
    N = len(y)
    S = np.sum(y)
    if S == 0 or S == N:
        return 0
    else:
        return -(S/N)*np.log(S/N) - ((N-S)/N)*np.log((N-S)/N)

original_entropy = entropy(y)
print("original entropy:", original_entropy)

original entropy: 0.6730116670092565


In [6]:
#SPLIT AT ATTRIBUTE 0
y_0_0 = y[X[:,0] == 0]
y_0_1 = y[X[:,0] == 1]
weight_0_0 = len(y_0_0)/len(y)
weight_0_1 = len(y_0_1)/len(y)
average_entropy_0 = (weight_0_0*entropy(y_0_0) + weight_0_1*entropy(y_0_1))
information_gain_0 = original_entropy - average_entropy_0
print("information gain at attribute 0:", information_gain_0)

#SPLIT AT ATTRIBUTE 1
y_1_0 = y[X[:,1] == 0]
y_1_1 = y[X[:,1] == 1]
weight_1_0 = len(y_1_0)/len(y)
weight_1_1 = len(y_1_1)/len(y)
average_entropy_1 = (weight_1_0*entropy(y_1_0) + weight_1_1*entropy(y_1_1))
information_gain_1 = original_entropy - average_entropy_1
print("information gain at attribute 1:", information_gain_1)

#SPLIT AT ATTRIBUTE 2
y_2_0 = y[X[:,2] == 0]
y_2_1 = y[X[:,2] == 1]
weight_2_0 = len(y_2_0)/len(y)
weight_2_1 = len(y_2_1)/len(y)
average_entropy_2 = (weight_2_0*entropy(y_2_0) + weight_2_1*entropy(y_2_1))
information_gain_2 = original_entropy - average_entropy_2
print("information gain at attribute 2:", information_gain_2)

#SPLIT AT ATTRIBUTE 3
y_3_0 = y[X[:,3] == 0]
y_3_1 = y[X[:,3] == 1]
weight_3_0 = len(y_3_0)/len(y)
weight_3_1 = len(y_3_1)/len(y)
average_entropy_3 = (weight_3_0*entropy(y_3_0) + weight_3_1*entropy(y_3_1))
information_gain_3 = original_entropy - average_entropy_3
print("information gain at attribute 3:", information_gain_3)


information gain at attribute 0: 0.38593024420737027
information gain at attribute 1: 0.29110316603236885
information gain at attribute 2: 0.005131640370881763
information gain at attribute 3: 0.06326870451113265


In [33]:
train_X= np.array([[ -7.983,   0.318,   1.177,  -0.075],
       [ -2.288,  -2.97 ,   1.557,  -3.241],
       [ -1.622,  11.014,   8.631,  -2.069],
       [ -5.75 ,   1.011,  14.284,  -3.099],
       [  0.935,  10.975,   7.959,  -4.048],
       [ -1.541,   7.003,  10.552,  -4.558],
       [ -0.344,   2.407,  -1.054,  -4.026],
       [ -1.759,  -0.67 ,   0.562,  -3.613],
       [ -1.126,  -4.047,   0.892,  -5.193],
       [ -2.327,  10.837,  11.682,  -2.213],
       [ -0.62 ,   4.928,  -0.732,  -4.64 ],
       [ -4.242,   7.423,  13.282,  -3.703],
       [ -1.113,   0.456,  -0.799,  -1.842],
       [ -0.161,   6.286,  -1.838,  -5.591],
       [ -2.592,   7.778,  12.245,  -7.002],
       [ -9.281,   2.353,   2.221,   0.251],
       [ -4.728,   5.334,  12.346,  -3.496],
       [  0.112,   3.716,   0.639,  -3.831],
       [ -8.759,  -0.261,   0.884,  -1.335],
       [ -3.675,   5.358,  11.416,  -3.644],
       [-12.174,  -4.295,   3.39 ,   1.336],
       [-11.718,  -3.836,   4.766,  -0.191],
       [ -1.28 ,  -0.809,   1.332,  -3.63 ],
       [ -4.129,   9.484,   9.761,  -1.132],
       [ -9.579,  -4.656,   2.802,  -0.113],
       [ -0.989,  11.243,  11.439,  -5.824],
       [ -8.123,  -0.8  ,   1.128,  -3.451],
       [ -5.206,   5.337,  12.67 ,  -2.111],
       [  0.961,   2.63 ,   0.075,  -4.746],
       [ -1.63 ,   7.706,  10.048,  -4.133]])
train_y= np.array([0, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 0, 1, 2, 0, 1, 0, 0, 2, 1, 0, 1, 0, 1, 2, 1])

In [34]:
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt

clf = LogisticRegression()
clf.fit(train_X, train_y)

test_x_0 =np.array([[ -2.457,   5.452,  13.113,  -4.819],
       [-10.195,  -0.629,   1.65 ,   0.67 ],
       [  0.571,   8.576,   9.002,  -6.633],
       [-10.688,  -3.278,   2.541,  -1.588]])
predict_prob = clf.predict_proba(test_x_0)
predict_prob_round = np.round(predict_prob, decimals=3)
print("predict prob:", predict_prob_round)

test_x_1 =np.array([[ -8.261,  -0.965,   1.238,  -2.658],
       [-10.909,  -3.602,   4.091,  -0.242],
       [ -9.492,  -0.179,   0.412,   1.098],
       [ -0.863,   3.818,  -2.278,  -2.43 ]])

print("predict:",clf.predict(test_x_1))

predict prob: [[0.    0.999 0.001]
 [0.998 0.001 0.001]
 [0.    0.978 0.022]
 [0.998 0.001 0.002]]
predict: [0 0 0 2]


In [36]:
train_X=np.array([[ 3.957, -7.186],
       [ 6.857, -0.822],
       [ 6.582, -1.077],
       [ 4.654, -7.987],
       [ 7.478, -1.931],
       [ 5.428, -8.313],
       [ 3.565, -7.913],
       [ 6.7  , -1.363],
       [ 4.623, -6.801],
       [ 6.033, -8.493],
       [ 6.548, -1.566],
       [ 5.168, -6.587],
       [ 5.073, -5.974],
       [ 6.333, -1.85 ],
       [ 3.938, -5.907],
       [ 6.813, -1.383],
       [ 6.556, -1.512],
       [ 6.578,  0.456],
       [ 4.682, -8.089],
       [ 5.265, -0.599],
       [ 3.721, -6.856],
       [ 7.461, -6.705],
       [ 5.786, -1.645],
       [ 6.46 , -1.797],
       [ 3.65 , -8.249],
       [ 9.457, -0.393],
       [ 2.895, -8.154],
       [ 7.965, -1.29 ],
       [ 3.926, -9.202],
       [ 8.016, -0.418]])
train_y=np.array([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0])

from sklearn.svm import SVC
#linear kernel
clf = SVC(kernel='linear')
clf.fit(train_X, train_y)
#get support vectors
print("support vectors:", clf.support_vectors_)
print("support vector indices:", clf.support_)

#rbf kernel
clf = SVC(kernel='rbf')
clf.fit(train_X, train_y)
#get support vectors
print("support vectors:", clf.support_vectors_)
print("support vector indices:", clf.support_)
print("support vector count:", clf.n_support_)

support vectors: [[ 6.333 -1.85 ]
 [ 5.073 -5.974]]
support vector indices: [13 12]
support vectors: [[ 7.478 -1.931]
 [ 6.333 -1.85 ]
 [ 5.786 -1.645]
 [ 6.46  -1.797]
 [ 5.168 -6.587]
 [ 5.073 -5.974]
 [ 3.938 -5.907]
 [ 7.461 -6.705]]
support vector indices: [ 4 13 22 23 11 12 14 21]
support vector count: [4 4]


In [38]:
data = np.load('finalnn_data.npz')
train_X = data['train_X']
train_y = data['train_y']
valid_X = data['valid_X']
valid_y = data['valid_y']

In [39]:
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
import tensorflow as tf

inputs = layers.Input(shape=(10,))
x = layers.Dense(20, activation='relu')(inputs)
x = layers.Dense(20, activation='relu')(x)
x = layers.Dropout(0.1)(x)
outputs = layers.Dense(3, activation='softmax')(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

model.summary()

Model: "model_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_7 (InputLayer)        [(None, 10)]              0         
                                                                 
 dense_18 (Dense)            (None, 20)                220       
                                                                 
 dense_19 (Dense)            (None, 20)                420       
                                                                 
 dropout_6 (Dropout)         (None, 20)                0         
                                                                 
 dense_20 (Dense)            (None, 3)                 63        
                                                                 
Total params: 703
Trainable params: 703
Non-trainable params: 0
_________________________________________________________________


In [40]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(train_X, train_y, epochs=100, batch_size=32,validation_data=(valid_X, valid_y))

Epoch 1/100
47/47 [==============================] - 0s 5ms/step - loss: 1.4612 - accuracy: 0.3273 - val_loss: 1.0174 - val_accuracy: 0.4880
Epoch 2/100
47/47 [==============================] - 0s 3ms/step - loss: 1.0052 - accuracy: 0.5220 - val_loss: 0.8394 - val_accuracy: 0.6740
Epoch 3/100
47/47 [==============================] - 0s 3ms/step - loss: 0.8253 - accuracy: 0.6300 - val_loss: 0.7092 - val_accuracy: 0.7240
Epoch 4/100
47/47 [==============================] - 0s 2ms/step - loss: 0.6934 - accuracy: 0.6993 - val_loss: 0.6077 - val_accuracy: 0.7640
Epoch 5/100
47/47 [==============================] - 0s 2ms/step - loss: 0.5896 - accuracy: 0.7727 - val_loss: 0.4996 - val_accuracy: 0.8480
Epoch 6/100
47/47 [==============================] - 0s 2ms/step - loss: 0.4703 - accuracy: 0.8313 - val_loss: 0.4071 - val_accuracy: 0.8880
Epoch 7/100
47/47 [==============================] - 0s 2ms/step - loss: 0.3837 - accuracy: 0.8747 - val_loss: 0.3476 - val_accuracy: 0.8940
Epoch 8/100
4